
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '@/component/navbar'
import Sidebar from '@/component/sidebar'
import Smallnavbar from '@/component/small'
import Box from '@/component/box'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <Smallnavbar/>
        <Box/>
        <Sidebar/>

        
      
    
        {children}</body>
      
    </html>
  );
}
